DEBUG = True

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASSETS_DIR = 'assets'
HOTAIR_BALLON_FILE = 'hotair_balloon.png'
HOTAIR_BALLON_BURN_FILE = 'hotair_balloon_burn.png'

HOTAIR_BALLON_SIZE = (100,100)

CANNONBALL_FILE = 'cannonball.png'
CANNONBALL_SIZE = (20, 20)

MINE_FILE = 'mine.png'
MINE_SIZE = (50, 50)

BACKGROUND_FILE = 'sky.png'

GRAVITY = 1
BALLON_DESC_RATE = 1
WIND = 1
BURN = -2